/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/match` | `/match`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientdetails` | `/patientdetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientslist` | `/patientslist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patient_match` | `/patient_match`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trialdetails` | `/trialdetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triallist` | `/triallist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TrialMatch` | `/TrialMatch`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/match` | `/match`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patientdetails` | `/patientdetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patientslist` | `/patientslist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/patient_match` | `/patient_match`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/trialdetails` | `/trialdetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/triallist` | `/triallist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TrialMatch` | `/TrialMatch`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/match${`?${string}` | `#${string}` | ''}` | `/match${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patientdetails${`?${string}` | `#${string}` | ''}` | `/patientdetails${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patientslist${`?${string}` | `#${string}` | ''}` | `/patientslist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/patient_match${`?${string}` | `#${string}` | ''}` | `/patient_match${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/trialdetails${`?${string}` | `#${string}` | ''}` | `/trialdetails${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/triallist${`?${string}` | `#${string}` | ''}` | `/triallist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TrialMatch${`?${string}` | `#${string}` | ''}` | `/TrialMatch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/match` | `/match`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientdetails` | `/patientdetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patientslist` | `/patientslist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/patient_match` | `/patient_match`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/trialdetails` | `/trialdetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triallist` | `/triallist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TrialMatch` | `/TrialMatch`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
